### PR TITLE
Front-end improvements

### PR DESCRIPTION
**Pull request by jmclaus**

### CODE REVIEW

**Comment by msegado** [comment]
Some additional todos for package.json:

- [ ] name: sketch2 => ? (may want to consider a scoped npm name, e.g. @sketchresponse/sketch-tool
- [ ] description: something more consistent with the docs
- [ ] dependencies: remove simulant? (don't think it's being used...)

**Comment by jmclaus** [comment]
@msegado In 'package.json', updated the name, description, version fields. Removed 'simulant' dependency that was part of the unit testing infrastructure.

**Comment by msegado** [comment]
Wohoo!

I actually have one tiny request: could we change the version to '1.0.0-rc' (release candidate) for now to avoid committing to the version number contract until I finish the other 1.0 milestones? Sorry, should have thought of that earlier...

Other than than, merge away! 😃

**Comment by jmclaus** [comment]
@msegado By far the easiest commit of the day! Done. Merging.

**Pull request merged**
